<?xml version="1.0" encoding="utf-8"?>
<TestRun id="e3b45221-22d0-4b3b-926b-4daa6ab0dfb0" name="anna@cloudtest-win10 2023-01-22 19:03:13" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-22T19:03:13.2373110+00:00" queuing="2023-01-22T19:03:13.2373115+00:00" start="2023-01-22T19:03:05.4676055+00:00" finish="2023-01-22T19:03:13.2794380+00:00" />
  <TestSettings name="default" id="cdd96136-a3c7-4d94-8ff6-63fa14e3aa51">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-22_19_03_13" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="a328f5a4-8936-48e1-a37b-09cfee255a11" testId="3b1868e8-34d3-e73d-cfed-ceff9555946a" testName="Tester.AzureUtils.AzureMembershipTableTests.MembershipTable_Azure_ReadRow_Insert_Read" computerName="cloudtest-win10" duration="00:00:01.8713156" startTime="2023-01-22T19:03:12.9121880+00:00" endTime="2023-01-22T19:03:12.9122335+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="a328f5a4-8936-48e1-a37b-09cfee255a11">
      <Output>
        <ErrorInfo>
          <Message>InsertRow failed&#xD;
Expected: True&#xD;
Actual:   False</Message>
          <StackTrace>   at UnitTests.MembershipTests.MembershipTableTestsBase.MembershipTable_ReadRow_Insert_Read(Boolean extendedProtocol) in C:\Users\anna\orleans\test\TesterInternal\MembershipTests\MembershipTableTestsBase.cs:line 178&#xD;
   at Tester.AzureUtils.AzureMembershipTableTests.MembershipTable_Azure_ReadRow_Insert_Read() in C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureMembershipTableTests.cs:line 82&#xD;
--- End of stack trace from previous location ---</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.AzureMembershipTableTests.MembershipTable_Azure_ReadRow_Insert_Read" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="3b1868e8-34d3-e73d-cfed-ceff9555946a">
      <Execution id="a328f5a4-8936-48e1-a37b-09cfee255a11" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.AzureMembershipTableTests" name="MembershipTable_Azure_ReadRow_Insert_Read" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="3b1868e8-34d3-e73d-cfed-ceff9555946a" executionId="a328f5a4-8936-48e1-a37b-09cfee255a11" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.29]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.50]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.52]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:04.46]       InsertRow failed&#xD;
[xUnit.net 00:00:04.46]       Expected: True&#xD;
[xUnit.net 00:00:04.46]       Actual:   False&#xD;
[xUnit.net 00:00:04.46]       Stack Trace:&#xD;
[xUnit.net 00:00:04.46]         C:\Users\anna\orleans\test\TesterInternal\MembershipTests\MembershipTableTestsBase.cs(178,0): at UnitTests.MembershipTests.MembershipTableTestsBase.MembershipTable_ReadRow_Insert_Read(Boolean extendedProtocol)&#xD;
[xUnit.net 00:00:04.46]         C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\AzureMembershipTableTests.cs(82,0): at Tester.AzureUtils.AzureMembershipTableTests.MembershipTable_Azure_ReadRow_Insert_Read()&#xD;
[xUnit.net 00:00:04.46]         --- End of stack trace from previous location ---&#xD;
[xUnit.net 00:00:04.49]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Min" timestamp="2023-01-22T19:03:12.9076486+00:00">
        <Text>[xUnit.net 00:00:04.46]     Tester.AzureUtils.AzureMembershipTableTests.MembershipTable_Azure_ReadRow_Insert_Read [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-22T19:03:13.0788495+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>