<?xml version="1.0" encoding="utf-8"?>
<TestRun id="74a82dc8-220e-4605-a5ec-61c0a962b2d2" name="anna@cloudtest-win10 2023-01-22 23:34:21" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-22T23:34:21.5836400+00:00" queuing="2023-01-22T23:34:21.5836410+00:00" start="2023-01-22T23:34:15.0908005+00:00" finish="2023-01-22T23:34:21.6200422+00:00" />
  <TestSettings name="default" id="a003bb74-f09e-4e7e-8ec5-7495a03e947b">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-22_23_34_21" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="5ccbe02d-c922-400e-925a-8d72d9eb4984" testId="60a46c89-261b-3ab8-4a85-671ac4a81765" testName="Tester.AzureUtils.AzureTableDataManagerTests.AzureTableDataManager_DeleteTableAsync" computerName="cloudtest-win10" duration="00:00:01.6552652" startTime="2023-01-22T23:34:21.2806132+00:00" endTime="2023-01-22T23:34:21.2806631+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="5ccbe02d-c922-400e-925a-8d72d9eb4984" />
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.AzureTableDataManagerTests.AzureTableDataManager_DeleteTableAsync" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="60a46c89-261b-3ab8-4a85-671ac4a81765">
      <Execution id="5ccbe02d-c922-400e-925a-8d72d9eb4984" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.AzureTableDataManagerTests" name="AzureTableDataManager_DeleteTableAsync" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="60a46c89-261b-3ab8-4a85-671ac4a81765" executionId="5ccbe02d-c922-400e-925a-8d72d9eb4984" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.25]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.46]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.48]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:03.24]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-22T23:34:21.4380172+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>