<?xml version="1.0" encoding="utf-8"?>
<TestRun id="37b5e54b-ae6b-4c9b-a272-e01968fcc736" name="anna@cloudtest-win10 2023-01-24 01:53:25" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-24T01:53:25.6909327+00:00" queuing="2023-01-24T01:53:25.6909333+00:00" start="2023-01-24T01:53:18.5441704+00:00" finish="2023-01-24T01:53:25.7265052+00:00" />
  <TestSettings name="default" id="7630e032-c74c-45fb-accb-90431059159d">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-24_01_53_25" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="045d33b7-69a4-429b-91fe-244e94a3acc9" testId="3573d3ee-354c-3210-4087-b549fe24d804" testName="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_CreateSiloEntryConditionally" computerName="cloudtest-win10" duration="00:00:01.9241895" startTime="2023-01-24T01:53:25.3915312+00:00" endTime="2023-01-24T01:53:25.3915787+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="045d33b7-69a4-429b-91fe-244e94a3acc9">
      <Output>
        <StdOut>ClusterId=test-29cb942b-21e9-472e-9d72-f216ab375d75 Generation=33530003&#xD;
Initializing SiloInstanceManager&#xD;
TestCleanup Timeout=00:01:00&#xD;
TestCleanup -  Finished</StdOut>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_CreateSiloEntryConditionally" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="3573d3ee-354c-3210-4087-b549fe24d804">
      <Execution id="045d33b7-69a4-429b-91fe-244e94a3acc9" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.SiloInstanceTableManagerTests" name="SiloInstanceTable_Op_CreateSiloEntryConditionally" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="3573d3ee-354c-3210-4087-b549fe24d804" executionId="045d33b7-69a4-429b-91fe-244e94a3acc9" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.32]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.54]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.55]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:03.59]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-24T01:53:25.5457390+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>