<?xml version="1.0" encoding="utf-8"?>
<TestRun id="2c953f79-c534-4b5b-b996-32d1c2b98c35" name="anna@cloudtest-win10 2023-01-24 01:52:57" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-24T01:52:57.3061122+00:00" queuing="2023-01-24T01:52:57.3061128+00:00" start="2023-01-24T01:52:50.5711758+00:00" finish="2023-01-24T01:52:57.3418490+00:00" />
  <TestSettings name="default" id="6ce42cc1-64fa-4ec3-a413-a141c7a6da2d">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-24_01_52_57" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="f60e04d4-74c1-4133-8a1e-03f2d7ac7491" testId="3573d3ee-354c-3210-4087-b549fe24d804" testName="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_CreateSiloEntryConditionally" computerName="cloudtest-win10" duration="00:00:01.9313195" startTime="2023-01-24T01:52:57.0054370+00:00" endTime="2023-01-24T01:52:57.0054913+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="f60e04d4-74c1-4133-8a1e-03f2d7ac7491">
      <Output>
        <StdOut>ClusterId=test-1b4fccfa-67f6-4e36-8a6c-90ed167f5861 Generation=33529975&#xD;
Initializing SiloInstanceManager&#xD;
TestCleanup Timeout=00:01:00&#xD;
TestCleanup -  Finished</StdOut>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_CreateSiloEntryConditionally" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="3573d3ee-354c-3210-4087-b549fe24d804">
      <Execution id="f60e04d4-74c1-4133-8a1e-03f2d7ac7491" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.SiloInstanceTableManagerTests" name="SiloInstanceTable_Op_CreateSiloEntryConditionally" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="3573d3ee-354c-3210-4087-b549fe24d804" executionId="f60e04d4-74c1-4133-8a1e-03f2d7ac7491" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.25]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.47]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.48]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:03.54]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-24T01:52:57.1604734+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>