<?xml version="1.0" encoding="utf-8"?>
<TestRun id="432b3679-1b31-4b29-a97d-fd05e63af3bc" name="anna@cloudtest-win10 2023-01-22 19:53:01" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-22T19:53:01.9720872+00:00" queuing="2023-01-22T19:53:01.9720881+00:00" start="2023-01-22T19:52:55.7375763+00:00" finish="2023-01-22T19:53:02.0112876+00:00" />
  <TestSettings name="default" id="542301de-d7e0-4951-b25f-c75990be3bb1">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-22_19_53_01" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="2ad99008-f239-4266-ac42-1c8449eac9ee" testId="60a46c89-261b-3ab8-4a85-671ac4a81765" testName="Tester.AzureUtils.AzureTableDataManagerTests.AzureTableDataManager_DeleteTableAsync" computerName="cloudtest-win10" duration="00:00:01.3479991" startTime="2023-01-22T19:53:01.6570182+00:00" endTime="2023-01-22T19:53:01.6570663+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="2ad99008-f239-4266-ac42-1c8449eac9ee" />
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.AzureTableDataManagerTests.AzureTableDataManager_DeleteTableAsync" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="60a46c89-261b-3ab8-4a85-671ac4a81765">
      <Execution id="2ad99008-f239-4266-ac42-1c8449eac9ee" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.AzureTableDataManagerTests" name="AzureTableDataManager_DeleteTableAsync" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="60a46c89-261b-3ab8-4a85-671ac4a81765" executionId="2ad99008-f239-4266-ac42-1c8449eac9ee" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.27]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.48]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.49]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:02.95]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-22T19:53:01.8140389+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>