<?xml version="1.0" encoding="utf-8"?>
<TestRun id="20d07263-8862-43f2-9e26-62c7c62ae9e7" name="anna@cloudtest-win10 2023-01-24 01:35:44" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-24T01:35:44.8122496+00:00" queuing="2023-01-24T01:35:44.8122504+00:00" start="2023-01-24T01:35:38.5089041+00:00" finish="2023-01-24T01:35:44.8509253+00:00" />
  <TestSettings name="default" id="375f9a1c-ee13-4c90-ba56-7274c75bc73b">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-24_01_35_44" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="7ecdfab8-3b21-4e15-9a8d-d834e2b5ecf7" testId="3573d3ee-354c-3210-4087-b549fe24d804" testName="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_CreateSiloEntryConditionally" computerName="cloudtest-win10" duration="00:00:01.5460676" startTime="2023-01-24T01:35:44.5084053+00:00" endTime="2023-01-24T01:35:44.5084982+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="7ecdfab8-3b21-4e15-9a8d-d834e2b5ecf7">
      <Output>
        <StdOut>ClusterId=test-4e7f5aca-9609-462c-8ff9-a0466eb1065a Generation=33528942&#xD;
Initializing SiloInstanceManager&#xD;
TestCleanup Timeout=00:01:00&#xD;
TestCleanup -  Finished</StdOut>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Op_CreateSiloEntryConditionally" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="3573d3ee-354c-3210-4087-b549fe24d804">
      <Execution id="7ecdfab8-3b21-4e15-9a8d-d834e2b5ecf7" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.SiloInstanceTableManagerTests" name="SiloInstanceTable_Op_CreateSiloEntryConditionally" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="3573d3ee-354c-3210-4087-b549fe24d804" executionId="7ecdfab8-3b21-4e15-9a8d-d834e2b5ecf7" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" failed="0" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.24]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.45]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.46]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:03.13]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-24T01:35:44.6635299+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>