<?xml version="1.0" encoding="utf-8"?>
<TestRun id="6fc9f842-c196-44d3-bf7d-fa526c747105" name="anna@cloudtest-win10 2023-01-24 01:55:14" runUser="cloudtest-win10\anna" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Times creation="2023-01-24T01:55:15.0130509+00:00" queuing="2023-01-24T01:55:15.0130515+00:00" start="2023-01-24T01:55:07.9048255+00:00" finish="2023-01-24T01:55:15.0540822+00:00" />
  <TestSettings name="default" id="96d7e51c-eb9f-4e5e-80c6-6327b47a6a43">
    <Deployment runDeploymentRoot="anna_cloudtest-win10_2023-01-24_01_55_14" />
  </TestSettings>
  <Results>
    <UnitTestResult executionId="2ca8db5f-4a96-4030-b9d8-4a12657ed1b1" testId="97391499-cea7-ece6-37da-e491ed23d91d" testName="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Register_CheckData" computerName="cloudtest-win10" duration="00:00:02.1539556" startTime="2023-01-24T01:55:14.7131159+00:00" endTime="2023-01-24T01:55:14.7131601+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="2ca8db5f-4a96-4030-b9d8-4a12657ed1b1">
      <Output>
        <StdOut>ClusterId=test-a974a669-1e2a-47b3-9fab-be66b3a4ae62 Generation=33530112&#xD;
Initializing SiloInstanceManager&#xD;
Start SiloInstanceTable_Register_CheckData&#xD;
MyEntry=OrleansSilo [ Deployment=test-a974a669-1e2a-47b3-9fab-be66b3a4ae62 LocalEndpoint=127.0.0.1 LocalPort=0 Generation=33530112 Host=127.0.0.1 Status= ProxyPort=30000 RoleName=MyRole SiloName=MyInstance UpgradeZone=0 FaultZone=0 StartTime=2023-01-24 01:55:13.271 GMT IAmAliveTime=]&#xD;
FindSiloEntry for SiloAddress=S127.0.0.1:0:33530112 PartitionKey=test-a974a669-1e2a-47b3-9fab-be66b3a4ae62 RowKey=127.0.0.1-0-33530112&#xD;
FindSiloEntry returning Data=(OrleansSilo [ Deployment=test-a974a669-1e2a-47b3-9fab-be66b3a4ae62 LocalEndpoint=127.0.0.1 LocalPort=0 Generation=33530112 Host=127.0.0.1 Status=Created ProxyPort=30000 RoleName=MyRole SiloName=MyInstance UpgradeZone=0 FaultZone=0 StartTime=2023-01-24 01:55:13.271 GMT IAmAliveTime=], W/"datetime'2023-01-24T01%3A55%3A13.4205636Z'")&#xD;
End SiloInstanceTable_Register_CheckData&#xD;
TestCleanup Timeout=00:01:00</StdOut>
        <ErrorInfo>
          <Message>System.AggregateException : One or more errors occurred. (The specified resource does not exist.
RequestId:6e4e1647-4002-0034-3696-2f78cf000000
Time:2023-01-24T01:55:14.6811643Z&#xD;
Status: 404 (Not Found)&#xD;
ErrorCode: ResourceNotFound&#xD;
&#xD;
Content:&#xD;
{"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:6e4e1647-4002-0034-3696-2f78cf000000\nTime:2023-01-24T01:55:14.6811643Z"}}}&#xD;
&#xD;
Headers:&#xD;
X-Content-Type-Options: REDACTED&#xD;
Cache-Control: no-cache&#xD;
DataServiceVersion: 3.0;&#xD;
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
)&#xD;
---- Azure.Data.Tables.TableTransactionFailedException : The specified resource does not exist.
RequestId:6e4e1647-4002-0034-3696-2f78cf000000
Time:2023-01-24T01:55:14.6811643Z&#xD;
Status: 404 (Not Found)&#xD;
ErrorCode: ResourceNotFound&#xD;
&#xD;
Content:&#xD;
{"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:6e4e1647-4002-0034-3696-2f78cf000000\nTime:2023-01-24T01:55:14.6811643Z"}}}&#xD;
&#xD;
Headers:&#xD;
X-Content-Type-Options: REDACTED&#xD;
Cache-Control: no-cache&#xD;
DataServiceVersion: 3.0;&#xD;
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
</Message>
          <StackTrace>   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)&#xD;
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#xD;
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)&#xD;
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)&#xD;
   at Orleans.Internal.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout) in C:\Users\anna\orleans\src\Orleans.Core\Async\TaskExtensions.cs:line 49&#xD;
   at Tester.AzureUtils.SiloInstanceTableManagerTests.Dispose() in C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\SiloInstanceTableManagerTests.cs:line 70&#xD;
   at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource) in /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs:line 79&#xD;
----- Inner Stack Trace -----&#xD;
   at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken)&#xD;
   at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)&#xD;
   at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken)&#xD;
   at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.DeleteTableEntriesAsync(List`1 collection) in C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs:line 483&#xD;
   at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteEntriesBatch(List`1 entriesList) in C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs:line 197&#xD;
   at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteTableEntries(String clusterId) in C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs:line 177</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
  <TestDefinitions>
    <UnitTest name="Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Register_CheckData" storage="c:\users\anna\orleans\test\extensions\testerazureutils\bin\debug\net7.0\tester.azureutils.dll" id="97391499-cea7-ece6-37da-e491ed23d91d">
      <Execution id="2ca8db5f-4a96-4030-b9d8-4a12657ed1b1" />
      <TestMethod codeBase="C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\bin\Debug\net7.0\Tester.AzureUtils.dll" adapterTypeName="executor://xunit/VsTestRunner2/netcoreapp" className="Tester.AzureUtils.SiloInstanceTableManagerTests" name="SiloInstanceTable_Register_CheckData" />
    </UnitTest>
  </TestDefinitions>
  <TestEntries>
    <TestEntry testId="97391499-cea7-ece6-37da-e491ed23d91d" executionId="2ca8db5f-4a96-4030-b9d8-4a12657ed1b1" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" passed="0" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
    <Output>
      <StdOut>[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.2)&#xD;
[xUnit.net 00:00:01.29]   Discovering: Tester.AzureUtils (method display = ClassAndMethod, method display options = None)&#xD;
[xUnit.net 00:00:01.52]   Discovered:  Tester.AzureUtils (found 246 test cases)&#xD;
[xUnit.net 00:00:01.53]   Starting:    Tester.AzureUtils (parallel test collections = off, max threads = 4)&#xD;
[xUnit.net 00:00:03.79]       System.AggregateException : One or more errors occurred. (The specified resource does not exist.
RequestId:6e4e1647-4002-0034-3696-2f78cf000000
Time:2023-01-24T01:55:14.6811643Z&#xD;
[xUnit.net 00:00:03.79]       Status: 404 (Not Found)&#xD;
[xUnit.net 00:00:03.79]       ErrorCode: ResourceNotFound&#xD;
[xUnit.net 00:00:03.79]       &#xD;
[xUnit.net 00:00:03.79]       Content:&#xD;
[xUnit.net 00:00:03.79]       {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:6e4e1647-4002-0034-3696-2f78cf000000\nTime:2023-01-24T01:55:14.6811643Z"}}}&#xD;
[xUnit.net 00:00:03.79]       &#xD;
[xUnit.net 00:00:03.79]       Headers:&#xD;
[xUnit.net 00:00:03.79]       X-Content-Type-Options: REDACTED&#xD;
[xUnit.net 00:00:03.79]       Cache-Control: no-cache&#xD;
[xUnit.net 00:00:03.79]       DataServiceVersion: 3.0;&#xD;
[xUnit.net 00:00:03.79]       Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
[xUnit.net 00:00:03.79]       )&#xD;
[xUnit.net 00:00:03.79]       ---- Azure.Data.Tables.TableTransactionFailedException : The specified resource does not exist.
RequestId:6e4e1647-4002-0034-3696-2f78cf000000
Time:2023-01-24T01:55:14.6811643Z&#xD;
[xUnit.net 00:00:03.79]       Status: 404 (Not Found)&#xD;
[xUnit.net 00:00:03.79]       ErrorCode: ResourceNotFound&#xD;
[xUnit.net 00:00:03.79]       &#xD;
[xUnit.net 00:00:03.79]       Content:&#xD;
[xUnit.net 00:00:03.79]       {"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:6e4e1647-4002-0034-3696-2f78cf000000\nTime:2023-01-24T01:55:14.6811643Z"}}}&#xD;
[xUnit.net 00:00:03.79]       &#xD;
[xUnit.net 00:00:03.79]       Headers:&#xD;
[xUnit.net 00:00:03.79]       X-Content-Type-Options: REDACTED&#xD;
[xUnit.net 00:00:03.79]       Cache-Control: no-cache&#xD;
[xUnit.net 00:00:03.79]       DataServiceVersion: 3.0;&#xD;
[xUnit.net 00:00:03.79]       Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8&#xD;
[xUnit.net 00:00:03.79]       &#xD;
[xUnit.net 00:00:03.79]       Stack Trace:&#xD;
[xUnit.net 00:00:03.79]            at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)&#xD;
[xUnit.net 00:00:03.79]            at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:03.79]            at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:03.79]            at System.Threading.Tasks.Task.Wait(TimeSpan timeout)&#xD;
[xUnit.net 00:00:03.79]         C:\Users\anna\orleans\src\Orleans.Core\Async\TaskExtensions.cs(49,0): at Orleans.Internal.OrleansTaskExtentions.WaitWithThrow(Task task, TimeSpan timeout)&#xD;
[xUnit.net 00:00:03.79]         C:\Users\anna\orleans\test\Extensions\TesterAzureUtils\SiloInstanceTableManagerTests.cs(70,0): at Tester.AzureUtils.SiloInstanceTableManagerTests.Dispose()&#xD;
[xUnit.net 00:00:03.79]         /_/src/xunit.execution/Extensions/ReflectionAbstractionExtensions.cs(79,0): at ReflectionAbstractionExtensions.DisposeTestClass(ITest test, Object testClass, IMessageBus messageBus, ExecutionTimer timer, CancellationTokenSource cancellationTokenSource)&#xD;
[xUnit.net 00:00:03.79]         ----- Inner Stack Trace -----&#xD;
[xUnit.net 00:00:03.79]            at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:03.79]            at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:03.79]            at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken)&#xD;
[xUnit.net 00:00:03.79]         C:\Users\anna\orleans\src\Azure\Shared\Storage\AzureTableDataManager.cs(483,0): at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.DeleteTableEntriesAsync(List`1 collection)&#xD;
[xUnit.net 00:00:03.79]         C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs(197,0): at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteEntriesBatch(List`1 entriesList)&#xD;
[xUnit.net 00:00:03.79]         C:\Users\anna\orleans\src\Azure\Orleans.Clustering.AzureStorage\OrleansSiloInstanceManager.cs(177,0): at Orleans.AzureUtils.OrleansSiloInstanceManager.DeleteTableEntries(String clusterId)&#xD;
[xUnit.net 00:00:03.79]       Output:&#xD;
[xUnit.net 00:00:03.79]         ClusterId=test-a974a669-1e2a-47b3-9fab-be66b3a4ae62 Generation=33530112&#xD;
[xUnit.net 00:00:03.79]         Initializing SiloInstanceManager&#xD;
[xUnit.net 00:00:03.79]         Start SiloInstanceTable_Register_CheckData&#xD;
[xUnit.net 00:00:03.79]         MyEntry=OrleansSilo [ Deployment=test-a974a669-1e2a-47b3-9fab-be66b3a4ae62 LocalEndpoint=127.0.0.1 LocalPort=0 Generation=33530112 Host=127.0.0.1 Status= ProxyPort=30000 RoleName=MyRole SiloName=MyInstance UpgradeZone=0 FaultZone=0 StartTime=2023-01-24 01:55:13.271 GMT IAmAliveTime=]&#xD;
[xUnit.net 00:00:03.79]         FindSiloEntry for SiloAddress=S127.0.0.1:0:33530112 PartitionKey=test-a974a669-1e2a-47b3-9fab-be66b3a4ae62 RowKey=127.0.0.1-0-33530112&#xD;
[xUnit.net 00:00:03.79]         FindSiloEntry returning Data=(OrleansSilo [ Deployment=test-a974a669-1e2a-47b3-9fab-be66b3a4ae62 LocalEndpoint=127.0.0.1 LocalPort=0 Generation=33530112 Host=127.0.0.1 Status=Created ProxyPort=30000 RoleName=MyRole SiloName=MyInstance UpgradeZone=0 FaultZone=0 StartTime=2023-01-24 01:55:13.271 GMT IAmAliveTime=], W/"datetime'2023-01-24T01%3A55%3A13.4205636Z'")&#xD;
[xUnit.net 00:00:03.79]         End SiloInstanceTable_Register_CheckData&#xD;
[xUnit.net 00:00:03.79]         TestCleanup Timeout=00:01:00&#xD;
[xUnit.net 00:00:03.83]   Finished:    Tester.AzureUtils&#xD;
</StdOut>
    </Output>
    <RunInfos>
      <RunInfo computerName="cloudtest-win10" outcome="Min" timestamp="2023-01-24T01:55:14.7065416+00:00">
        <Text>[xUnit.net 00:00:03.79]     Tester.AzureUtils.SiloInstanceTableManagerTests.SiloInstanceTable_Register_CheckData [FAIL]</Text>
      </RunInfo>
      <RunInfo computerName="cloudtest-win10" outcome="Warning" timestamp="2023-01-24T01:55:14.8656217+00:00">
        <Text>Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.</Text>
      </RunInfo>
    </RunInfos>
  </ResultSummary>
</TestRun>